Revert "CI: Add workaround to current GHA issues around Homebrew git"
This reverts commit 4c78bd42e6b354ede7838fc09da9275e538c64b3.
Now this command fails with a following message.
  Error: No such keg: /usr/local/Cellar/git@2.35.1